# Generated by Django 5.1.2 on 2026-05-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_id', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_status', models.CharField(choices=[('working', 'Working'), ('fused', 'Fused'), ('day', 'Burning During Day')], max_length=20)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.pole')),
            ],
        ),
    ]
