# Generated by Django 5.1.2 on 2026-05-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_pole_status_report_repair_status_report_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='pole_image',
            field=models.ImageField(blank=True, null=True, upload_to='pole_images/'),
        ),
        migrations.AddField(
            model_name='pole',
            name='pole_number_image',
            field=models.ImageField(blank=True, null=True, upload_to='pole_number_images/'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('fused', 'Fused'), ('day', 'Burning During Day')], default='working', max_length=20),
        ),
    ]
