# Generated by Django 6.0.5 on 2026-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_pole_full_address_pole_latitude_pole_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pole',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='pole',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pole',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pole',
            name='pole_image',
        ),
        migrations.RemoveField(
            model_name='pole',
            name='pole_number_image',
        ),
        migrations.AddField(
            model_name='report',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pole_image',
            field=models.ImageField(blank=True, null=True, upload_to='pole_images/'),
        ),
        migrations.AddField(
            model_name='report',
            name='pole_number_image',
            field=models.ImageField(blank=True, null=True, upload_to='pole_number_images/'),
        ),
    ]
