# Generated by Django 5.1.2 on 2026-05-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_pole_full_address_remove_pole_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
