# Generated by Django 5.1.2 on 2026-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('fused', 'Fused'), ('burning during day', 'Burning During Day')], default='working', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_status',
            field=models.CharField(choices=[('working', 'Working'), ('fused', 'Fused'), ('burning during day', 'Burning During Day')], max_length=20),
        ),
    ]
